name: Treehole Push

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Show repository files
        run: |
          pwd
          ls -la
          ls -la app

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env
        run: |
          cat > .env <<EOF
          TREEHOLE_BASE_URL=https://treehole.pku.edu.cn
          TREEHOLE_SEARCH_API=/chapi/api/v3/hole/list_comments
          TREEHOLE_AUTHORIZATION=${{ secrets.TREEHOLE_AUTHORIZATION }}
          TREEHOLE_COOKIE=${{ secrets.TREEHOLE_COOKIE }}
          TREEHOLE_X_XSRF_TOKEN=${{ secrets.TREEHOLE_X_XSRF_TOKEN }}
          TREEHOLE_UUID=${{ secrets.TREEHOLE_UUID }}
          TREEHOLE_TIMEOUT=15

          SERVERCHAN_SENDKEY=${{ secrets.SERVERCHAN_SENDKEY }}

          RUNNER_INTERVAL_SECONDS=6000
          RECENT_DAYS=7
          SEARCH_PAGE=1
          SEARCH_LIMIT=20
          SEARCH_COMMENT_LIMIT=10
          EOF

      - name: Run script
        run: python -m app.runner_core
